### ISSUE TITLE
UI Refresh Issues

### ISSUE THREAD

**Issue by Shopper7** [Marda33/SkeuoCord#81]
As per title. 

Icons, sizing, and other things are broken. The theme, like other themes, is completely unusable with the new update.

This is happening on:
stable 365373 (81183a6) 
Host 1.0.9180 x64 (58115) 
Vencord 6cccb54 (Standalone)

**Comment by Marda33** [comment]
I'll look into fixing SkeuoCord for the UI refresh after its rollout is finalized. I haven't recived it on my end yet.

**Comment by bigwilko** [comment]
Are you going to fix it soon? I received the UI refresh 3 weeks ago

**Comment by Marda33** [comment]
Unfortunately all of  the accounts I have access to still have not gotten the UI refresh. 
So until Discord rolls it out for everyone I don't believe there is a way to fix SkeuoCord for it, and fixing the refresh would break the theme for users that still have the old UI.

**Comment by Shopper7** [comment]
Did you maybe receive it yet?

**Comment by Marda33** [comment]
I've finally managed to force enable the new UI with an experiments plugin. 
I'll be uploading a version that should fix the major issues soon, and will fix the smaller ones as I find more time.

**Comment by Marda33** [comment]
You can replace SkeuoCordBase in the theme import with SkeuoCord_Refresh for support for the new UI.
BGImport support and further tweaking will come soon. Let me know if it works for you.

**Comment by Shopper7** [comment]
It works for the most part! 
One issue Ive noticed is this (see image), all settings like that appear to be broken still.

![Image](https://github.com/user-attachments/assets/152956a5-e605-42c0-83c9-1e73613746a3)

**Comment by Marda33** [comment]
Most of these bugs should be fixed in the new refresh version.
Support for BGImport has also been added. Enter `SkeuoCord_Refresh_CustomBG` in the theme import to use it.

**Comment by Shopper7** [comment]
Hey, do I need to change anything on my end if I dont intend on using the Custom BG?

I've loaded up discord and all of the issues persist, so Im presuming that its caching an older version.

**Comment by Shopper7** [comment]
Tried reloading it, issue persists.

![Image](https://github.com/user-attachments/assets/801990f9-f0a1-4211-b75d-ed47b0e63f0e)

Does this look right to you? It worked up to now so I assume that its right but Id like to confirm it.

**Comment by Shopper7** [comment]
Ok, so I was a bit naive and tested only one of the few bugs.

So: input bar height is fixed
Jump to present is fixed
Most used emotes are fixed

BUT

The issue with icons in the plugins, themes etc submenus (on vencord) persists.

**Comment by Marda33** [comment]
Changes for the UI refresh have now been merged into the main `SkeuoCordBase` import. `SkeuoCord_BGImport/BGImport_ExtTransp` work as usual again and `SkeuoCord_Refresh` - `SkeuoCord_Refresh_CustomBG` have been deleted. 
Let me know here if you find bugs besides the ones already reported.

**Comment by Marda33** [comment]
Would you prefer if I brought back the pre-refresh UI titlebar to the refresh UI or keep the refersh titlebar as is?

**Comment by Shopper7** [comment]
Id need to see the exact difference in order to decide, to be honest!

**Comment by Marda33** [comment]
![Image](https://github.com/user-attachments/assets/807c7fb4-d359-488e-b9c4-162bba7a2d05)
Top is the pre-refresh titlebar ported back while bottom is the current refresh one.

**Comment by Marda33** [comment]
The 1.38.1 update reverts back to the pre-refresh titlebar. You should be able to get it in a couple minutes by refreshing Discord.
Let me know if it works for you.

**Comment by Shopper7** [comment]
yep, noticed it immediately when I opened up discord now, works flawlessly!

**Comment by Marda33** [comment]
I assume this can't be fixed since the channel toolbar icons have to be offset a set amount for the inbox and help icons to fit in, and that can't be dynamically updated to also fit the update icon. I'll see if anything can be done though.

**Comment by Marda33** [comment]
Vencord settings bugs should now be fixed with version 1.38.2. Have they been fixed for you?

**Comment by Shopper7** [comment]
Yep, they're fixed!
